version: 2.1
orbs:
  ruby: circleci/ruby@1.0.0

jobs:
  build:
    executor:
      name: ruby/default
      tag: "2.7.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config set path vendor/bundle
      - run: bundle install
      - save_cache:
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rubocop:
    executor:
      name: ruby/default
      tag: "2.7.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config set path vendor/bundle
      - run: bundle install
      - run: bundle exec rubocop
  fasterer:
    executor:
      name: ruby/default
      tag: "2.7.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle config set path vendor/bundle
      - run: bundle install
      - run: bundle exec fasterer


workflows:
  version: 2
  build_lint_spec:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - fasterer:
          requires:
            - rubocop
#- ruby/bundle-install

# version: 2.1
# orbs:
#   ruby: circleci/ruby@1.0.0

# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.7.1
#     executor: ruby/default
#     steps:
#       - checkout
#       - run:
#         name: "Testing"
#         command: echo "Hi"
