version: 2.1
orbs:
  ruby: circleci/ruby@1.0.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
        name: "Which bundler?"
        command: bundle -v
