version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.7.1

caches:
  - &bundle_cache_full v1-gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  - &bundle_cache_branch v1-gem-cache-{{ .Branch }}
  - &bundle_cache_repo v1-gem-cache

commands:
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache_branch
            - *bundle_cache_repo
      - run: bundle config set path vendor/bundle
      - run: bundle install
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle
  run_rubocop:
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_fasterer:
    steps:
      - run: bundle exec fasterer

jobs:
  rubocop:
    executor: default
    steps:
      - setup_environment
      - run_rubocop
  fasterer:
    executor: default
    steps:
      - setup_environment
      - run_fasterer

workflows:
  version: 2
  lint_spec:
    jobs:
      - rubocop
      - fasterer
#- ruby/bundle-install

# version: 2.1
# orbs:
#   ruby: circleci/ruby@1.0.0

# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.7.1
#     executor: ruby/default
#     steps:
#       - checkout
#       - run:
#         name: "Testing"
#         command: echo "Hi"
